spring:
  liquibase:
    contexts: default
  datasource:
    tomcat:
      validation-query: /* ping */ SELECT 1;
      test-on-borrow: true
      testWhileIdle: true
      max-wait: 30000
      max-active: 400
    username: root
    password: samadal
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://15.165.176.81:3306/emotions?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=UTC
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        jdbc:
          time_zone: UTC
          batch_size: 200
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: none
  data:
    rest:
      base-path: /v1



---
log4jdbc.spylogdelegator.name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
log4jdbc.dump.sql.maxlinelength: 0
---
app.jwtSecret: JWTSuperSecretKey
app.jwtExpirationInMs: 1800000
app.jwt.claims.refresh.name: Refresh
---
logging:
  file: logs/application.log
  level:
    org.springframework.web: INFO
    org.springframework.data.rest: INFO
---
spring.profiles: logging-info
logging:
  file: logs/application.log
  level:
    org.springframework.web: INFO
    org.springframework.data.rest: INFO
---
spring.profiles: logging-debug
logging:
  file: logs/application.log
  level:
    org.springframework.web: DEBUG
    org.springframework.data.rest: DEBUG

---
spring.profiles: logging-daily
logging:
  config: classpath:logback-spring.xml

---
